### ISSUE TITLE
[Android Bootcamp] Project0: TodoApp - Ready for Review

### ISSUE THREAD

**Issue by chenlego** [AndroidTrainingL2/Android-Pre-work-Todo-App#1]
Hi,
Sorry, I forgot to issue my pre-work to you yesterday.
Please help to review it..thanks.

My app is complete, please review. Thanks.
/cc @codepathreview @codepath.

My Name: Lego Chen

**Comment by nidhi1608** [comment]
Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

**Comment by chenlego** [comment]
Got it , thanks .
